# Generated by Django 5.2.5 on 2025-08-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='mit_chatbot.user'),
        ),
    ]
