# Generated by Django 5.2.5 on 2025-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0002_escalationticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL to extract content from', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True),
        ),
    ]
