# Generated by Django 5.2.5 on 2025-08-09 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0003_document_source_url_document_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
