# Generated by Django 5.2.5 on 2025-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0004_rename_user_customuser_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
