# Generated by Django 5.2.5 on 2025-08-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0006_academicsession_department_faculty_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_start',
        ),
    ]
