# Generated by Django 5.2.5 on 2025-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0007_remove_semester_registration_end_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
