# Generated by Django 5.2.5 on 2025-08-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_chatbot', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
    ]
